version: '3'
services:
  prometheus:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
  node-exporter:
    build:
      context: .
      dockerfile: DockerfileNodeExporter
    ports:
      - "9100:9100"
