server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: info, health, prometheus
  metrics:
    export:
      atlas:
        enabled: false
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/helloapp?autoReconnect=true
    username: root
    password: baza1
  jpa:
    show-sql: false
    hibernate:
      generate_statistics: true
      ddl-auto: create

#logging.level.org.springframework.transaction.interceptor: TRACE